[package]
name = "bpf-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpf-ins = { path="../bpf-ins" }
byteorder = "1.4.3"
num_cpus = "0.2"
peginator = "0.2.0"
peginator_macro = "0.2.0"
